---
- name: Check if '/opt/.ansible_state/roles/lua' exists
  stat:
    path: /opt/.ansible_state/roles/lua
  register: ansible_state_roles_lua
- name: Installing lua
  block:
  - name: Download lua-{{ lua_version }}.tar.gz
    get_url:
      url: http://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz
      dest: /opt
    become: yes
  - name: Unarchive lua-{{ lua_version }}.tar.gz
    unarchive:
      src: /opt/lua-{{ lua_version }}.tar.gz
      dest: /opt
      remote_src: yes
    become: yes
  - name: Install packages gcc g++ make libreadline-dev
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc
      - g++
      - make
      - libreadline-dev
    become: yes
  - name: Buuilding /opt/lua-{{ lua_version }}
    command: make linux test
    args:
      chdir: /opt/lua-{{ lua_version }}
      creates: /opt/lua-{{ lua_version }}/src/lua
  - name: Create '/opt/.ansible_state' folder
    file:
      path: /opt/.ansible_state
      state: directory
    become: yes
  - name: Create '/opt/.ansible_state/roles' folder
    file:
      path: /opt/.ansible_state/roles
      state: directory
    become: yes
  - name: Create '/opt/.ansible_state/roles/lua' file
    file:
      path: /opt/.ansible_state/roles/lua
      state: touch
    become: yes
  when: not ansible_state_roles_lua.stat.exists 
