all:
  hosts:
  children:
    common:
      hosts:
        45.32.238.119:
    postgres:
      hosts:
        45.32.238.119:
    idempiere_common:
      hosts:
        45.32.238.119:
    idempiere_db:
      hosts:
        45.32.238.119:
    idempiere:
      hosts:
        45.32.238.119:
    idempiere_standalone_db:
      hosts:
        136.244.110.122:
    idempiere_standalone_server:
      hosts:
        136.244.103.195:

