all:
  hosts:
  children:
    common:
      hosts:
        95.179.155.167:
    postgres:
      hosts:
        95.179.155.167:
    idempiere_common:
      hosts:
        95.179.155.167:
    idempiere_db:
      hosts:
        95.179.155.167:
    idempiere:
      hosts:
        95.179.155.167:

