---
- name: Check if '/opt/.ansible_state/roles/postgres' exists
  stat:
    path: /opt/.ansible_state/roles/postgres
  register: ansible_state_roles_postgres
- name: Installing postgres
  block:
  - name: Install packages postgresql, postgresql-contrib
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - "postgresql"
      - "postgresql-contrib"
    become: yes
  - name: Install psycopg2 needed for ansible postgresql commands
    pip: name=psycopg2-binary
    become: yes
  - name: Change password for user 'postgres'
    postgresql_query: 
      db: postgres
      query: alter user postgres password %(password)s
      named_args:
        password: "{{ role_postgres_postgres_password }}"
    become: yes
    become_user: postgres
  - name: Replace "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    template:
      src: pg_hba.conf
      dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
      owner: postgres
      group: postgres
      mode: 0600
    become: yes
  - name: Replace "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    template:
      src: postgresql.conf
      dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
      owner: postgres
      group: postgres
      mode: 0600
    become: yes
  - name: Restart postgresql.service
    systemd:
      name: postgresql
      state: restarted
    become: yes
  - name: Create '/opt/.ansible_state' folder
    file:
      path: /opt/.ansible_state
      state: directory
    become: yes
  - name: Create '/opt/.ansible_state/roles' folder
    file:
      path: /opt/.ansible_state/roles
      state: directory
    become: yes
  - name: Create '/opt/.ansible_state/roles/postgres' file
    file:
      path: /opt/.ansible_state/roles/postgres
      state: touch
    become: yes
  - name: Create '/opt/.ansible_state/roles/postgres' file
    file:
      path: /opt/.ansible_state/roles/postgres
      state: touch
    become: yes
  when: not ansible_state_roles_postgres.stat.exists 
