- hosts: onestopsoft
  vars_files:
    - ../../vars/{{ env }}/main.yml
    - ../../vars/{{ env }}/vault/main.yml
  roles:
    - haproxy
  tasks:
  - name: Configure haproxy.
    import_tasks: common/haproxy.yml

